# Crypto Ecosystem Analyzer Configuration - Organization-Based
# This file controls all the parameters for the analysis
# Updated for comprehensive OSO schema with reasonable performance limits

[general]
# Output directory for CSV files
output_dir = "./raw"

# Date range for contributions (in days from now)
# Set to 0 to include all historical data
days_back = 730  # 0 = all time, 365 = last year, 730 = last 2 years

# List of seed repositories to analyze
# Core repositories that define the AI ecosystem
seed_repos = [
]

# Analysis configuration
[analysis]
# Enable extended repository and contributor analysis (set to false to only analyze seed repos)
extended_analysis = true
# Minimum commits threshold for all analysis (repositories, core contributors, extended contributors)
min_commits = 2
# Minimum core contributors threshold for all analysis (seed repos, extended repos, all phases)
min_core_contributors = 2
# Maximum number of extended repositories to include (sorted by stars)
max_extended_repos = 1000


# Event type weights for trust calculations
[weights]
# User-to-repo trust weights (higher values indicate stronger positive signals)
[weights.user_to_repo]
commit_code = 5
pull_request_opened = 20
pull_request_merged = 10
starred = 5
issue_opened = 10
forked = 1

# Repo-to-user trust weights (typically lower values, focused on core contributions)
[weights.repo_to_user]
commit_code = 3
pull_request_opened = 5
pull_request_merged = 1

[filters]
# Contributor filters
exclude_bots = true  # Set to true to exclude bot accounts
bot_keywords = ["bot", "dependabot", "mergify", "renovate", "github-actions", "semantic-release"]
